[General]
# ============================================================================
# Clock
# ============================================================================
# 12 hours or 24 Hours true=12 [true | false]
ap=false

# Maincard blur strength [0.0 to 1.0] (not implemented as of now)
blur=0.8

# ============================================================================
# COLOR SCHEME
# ============================================================================
# Do not touch these! (auto-synced by Caelestia)
background=#0e1511
mainCard=#0e1511
subComponents=#1a211d
text=#dde4dd
textDark=#86cfff
primary=#0aba7d
onPrimary=#003d22
secondary=#9ed2b3
onSecondary=#213528
tertiary=#86cfff
onTertiary=#1a211d
onSuccess=#213528
inverseOnSurface=#2b322d
surface=#1f1f1f
surfaceVariant=#353535
surfaceContainerLow=#0e1511
surfaceContainer=#0e1511
surfaceContainerHigh=#1a211d
outline=#353535
error=#ffb4ab
