[General]
# ============================================================================
# TYPOGRAPHY
# ============================================================================
# Font Family
fontFamily="Rubik"

# Font Size
FontSize=11

# Avatar Size
AvatarSize=120

# ============================================================================
# BORDER RADIUS (roundness)
# ============================================================================
# UI Elements (inputs, combo boxes, toast)
elementRadius=25

# Login Card
cardRadius=80

# ============================================================================
# VISUAL EFFECTS
# ============================================================================
# Card Drop shadows [true | false]
dropShadows=true

# Background blur [true | false]
blurEnabled=true

# Background blur strength [0.0 to 1.0]
blurStrength=0.6

# Card Opacity [0 to 1]
cardOpacity=0.50

# Background overlay opacity [0 to 1]
overlayOpacity=0.4

# ============================================================================
# DEBUG
# ============================================================================
# Debug mode (enable debug keyboard shortcuts) [true | false]
debugMode=false

# ============================================================================
# COLOR SCHEME
# ============================================================================
# Do not touch these! (auto-synced by Caelestia)
mPrimary=#4cdadb
mOnPrimary=#002022

mSecondary=#95f4f5
mOnSecondary=#003738

mTertiary=#86d0ff
mOnTertiary=#00344d

mError=#ffb4ab
mOnError=#690005

mSurface=#131313
mOnSurface=#e2e2e2

mSurfaceVariant=#353535
mOnSurfaceVariant=#919191

mOutline=#7d7d7d
mShadow=#000000

mHover=#4cdadb
mOnHover=#002022
